In [49]:
import pandas as pd
df = pd.read_csv('team_atts_sp.csv',sep=',')
df

,id,team_fifa_api_id,team_api_id,date,buildUpPlaySpeed,buildUpPlaySpeedClass,buildUpPlayDribbling,buildUpPlayDribblingClass,buildUpPlayPassing,buildUpPlayPassingClass,...,chanceCreationShooting,chanceCreationShootingClass,chanceCreationPositioningClass,defencePressure,defencePressureClass,defenceAggression,defenceAggressionClass,defenceTeamWidth,defenceTeamWidthClass,defenceDefenderLineClass
0,40,1861,9865,2010-02-22 00:00:00,65,Balanced,NaN,Little,45,Mixed,...,70,Lots,Organised,70,High,65,Press,30,Narrow,Cover
1,41,1861,9865,2011-02-22 00:00:00,55,Balanced,NaN,Little,53,Mixed,...,69,Lots,Organised,58,Medium,68,Double,67,Wide,Cover
2,42,1861,9865,2012-02-22 00:00:00,42,Balanced,NaN,Little,70,Long,...,40,Normal,Organised,37,Medium,53,Press,45,Normal,Cover
3,43,1861,9865,2013-09-20 00:00:00,46,Balanced,NaN,Little,65,Mixed,...,40,Normal,Organised,37,Medium,53,Press,45,Normal,Cover
4,44,1861,9865,2014-09-19 00:00:00,46,Balanced,41.0,Normal,65,Mixed,...,40,Normal,Organised,37,Medium,53,Press,45,Normal,Cover
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,1446,244,8394,2011-02-22 00:00:00,43,Balanced,NaN,Little,40,Mixed,...,42,Normal,Organised,38,Medium,40,Press,53,Normal,Cover
183,1447,244,8394,2012-02-22 00:00:00,34,Balanced,NaN,Little,23,Short,...,57,Normal,Organised,51,Medium,46,Press,61,Normal,Cover
184,1448,244,8394,2013-09-20 00:00:00,38,Balanced,NaN,Little,23,Short,...,57,Normal,Organised,51,Medium,46,Press,61,Normal,Cover
185,1449,244,8394,2014-09-19 00:00:00,38,Balanced,48.0,Normal,35,Mixed,...,57,Normal,Organised,51,Medium,46,Press,61,Normal,Cover
186,1450,244,8394,2015-09-10 00:00:00,52,Balanced,52.0,Normal,50,Mixed,...,57,Normal,Organised,48,Medium,43,Press,49,Normal,Cover

In [34]:
df2['team_fifa_api_id'] = df2['team_fifa_api_id'].apply(lambda x: int(x))
df2

,id,team_api_id,team_fifa_api_id,team_long_name,team_short_name
0,43035,10267,461,Valencia CF,VAL
1,43036,8661,453,RCD Mallorca,MAL
2,43037,8371,479,CA Osasuna,OSA
3,43038,10205,483,Villarreal CF,VIL
4,43039,9783,242,RC Deportivo de La Coruña,COR
5,43040,8633,243,Real Madrid CF,REA
6,43041,8388,477,CD Numancia,NUM
7,43042,8634,241,FC Barcelona,BAR
8,43043,8696,456,Racing Santander,SAN
9,43044,8302,481,Sevilla FC,SEV
10,43045,9869,459,Real Sporting de Gijón,SPG
11,43046,8305,1860,Getafe CF,GET
12,43047,8603,449,Real Betis Balompié,BET
13,43048,8479,571,RC Recreativo,HUE
14,43049,8558,452,RCD Espanyol,ESP
15,43050,10281,462,Real Valladolid,VAL
16,43051,8315,448,Athletic Club de Bilbao,BIL
17,43052,9865,1861,UD Almería,ALM
18,43053,9906,240,Atlético Madrid,AMA
19,43054,9864,573,Málaga CF,MAL
20,43800,9868,1742,Xerez Club Deportivo,XER
21,43803,8394,244,Real Zaragoza,ZAR
22,43804,9867,260,CD Tenerife,TEN
23,44557,10278,100879,Hércules Club de Fútbol,HER
24,44565,8581,1853,Levante UD,LEV
25,44569,8560,457,Real Sociedad,SOC
26,45330,7878,110832,Granada CF,GRA
27,45333,8370,480,Rayo Vallecano,RAY
28,46087,9910,450,RC Celta de Vigo,CEL
29,46848,10268,468,Elche CF,ELC
30,47605,8372,467,SD Eibar,EIB
31,47612,7869,1867,Córdoba CF,COR
32,48358,8306,472,UD Las Palmas,LAS

In [41]:
# fusionamos csv's

## team_atts_sp con la columna de nombre largo

In [126]:
df_fus = df.merge(df2[['team_fifa_api_id', 'team_long_name']], on='team_fifa_api_id', how='left')
df_fus

,id,team_fifa_api_id,team_api_id,date,buildUpPlaySpeed,buildUpPlaySpeedClass,buildUpPlayDribbling,buildUpPlayDribblingClass,buildUpPlayPassing,buildUpPlayPassingClass,...,chanceCreationShootingClass,chanceCreationPositioningClass,defencePressure,defencePressureClass,defenceAggression,defenceAggressionClass,defenceTeamWidth,defenceTeamWidthClass,defenceDefenderLineClass,team_long_name
0,40,1861,9865,2010-02-22 00:00:00,65,Balanced,NaN,Little,45,Mixed,...,Lots,Organised,70,High,65,Press,30,Narrow,Cover,UD Almería
1,41,1861,9865,2011-02-22 00:00:00,55,Balanced,NaN,Little,53,Mixed,...,Lots,Organised,58,Medium,68,Double,67,Wide,Cover,UD Almería
2,42,1861,9865,2012-02-22 00:00:00,42,Balanced,NaN,Little,70,Long,...,Normal,Organised,37,Medium,53,Press,45,Normal,Cover,UD Almería
3,43,1861,9865,2013-09-20 00:00:00,46,Balanced,NaN,Little,65,Mixed,...,Normal,Organised,37,Medium,53,Press,45,Normal,Cover,UD Almería
4,44,1861,9865,2014-09-19 00:00:00,46,Balanced,41.0,Normal,65,Mixed,...,Normal,Organised,37,Medium,53,Press,45,Normal,Cover,UD Almería
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,1446,244,8394,2011-02-22 00:00:00,43,Balanced,NaN,Little,40,Mixed,...,Normal,Organised,38,Medium,40,Press,53,Normal,Cover,Real Zaragoza
183,1447,244,8394,2012-02-22 00:00:00,34,Balanced,NaN,Little,23,Short,...,Normal,Organised,51,Medium,46,Press,61,Normal,Cover,Real Zaragoza
184,1448,244,8394,2013-09-20 00:00:00,38,Balanced,NaN,Little,23,Short,...,Normal,Organised,51,Medium,46,Press,61,Normal,Cover,Real Zaragoza
185,1449,244,8394,2014-09-19 00:00:00,38,Balanced,48.0,Normal,35,Mixed,...,Normal,Organised,51,Medium,46,Press,61,Normal,Cover,Real Zaragoza
186,1450,244,8394,2015-09-10 00:00:00,52,Balanced,52.0,Normal,50,Mixed,...,Normal,Organised,48,Medium,43,Press,49,Normal,Cover,Real Zaragoza

## team_atts_sp con el groupby hecho

In [114]:
df_grb = df_fus.groupby('team_fifa_api_id').agg(list)
df_grb

,id,team_api_id,date,buildUpPlaySpeed,buildUpPlaySpeedClass,buildUpPlayDribbling,buildUpPlayDribblingClass,buildUpPlayPassing,buildUpPlayPassingClass,buildUpPlayPositioningClass,...,chanceCreationShootingClass,chanceCreationPositioningClass,defencePressure,defencePressureClass,defenceAggression,defenceAggressionClass,defenceTeamWidth,defenceTeamWidthClass,defenceDefenderLineClass,team_long_name
team_fifa_api_id,,,,,,,,,,,,,,,,,,,,,
240,"[95, 96, 97, 98, 99, 100]","[9906, 9906, 9906, 9906, 9906, 9906]","[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[64, 57, 47, 47, 47, 57]","[Balanced, Balanced, Balanced, Balanced, Balan...","[nan, nan, nan, nan, 52.0, 50.0]","[Little, Little, Little, Little, Normal, Normal]","[30, 54, 51, 51, 51, 50]","[Short, Mixed, Mixed, Mixed, Mixed, Mixed]","[Free Form, Organised, Organised, Organised, O...",...,"[Lots, Lots, Normal, Normal, Normal, Normal]","[Free Form, Organised, Organised, Organised, O...","[70, 58, 52, 52, 52, 49]","[High, Medium, Medium, Medium, Medium, Medium]","[34, 48, 37, 37, 37, 42]","[Press, Press, Press, Press, Press, Press]","[55, 54, 55, 55, 55, 52]","[Normal, Normal, Normal, Normal, Normal, Normal]","[Offside Trap, Cover, Cover, Cover, Cover, Cover]","[Atlético Madrid, Atlético Madrid, Atlético Ma..."
241,"[119, 120, 121, 122, 123, 124]","[8634, 8634, 8634, 8634, 8634, 8634]","[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[42, 43, 24, 35, 35, 36]","[Balanced, Balanced, Slow, Balanced, Balanced,...","[nan, nan, nan, nan, 35.0, 35.0]","[Little, Little, Little, Little, Normal, Normal]","[30, 34, 25, 32, 32, 51]","[Short, Mixed, Short, Short, Short, Mixed]","[Free Form, Free Form, Free Form, Free Form, F...",...,"[Lots, Lots, Normal, Normal, Normal, Normal]","[Free Form, Free Form, Free Form, Free Form, F...","[70, 67, 66, 61, 61, 61]","[High, High, Medium, Medium, Medium, Medium]","[30, 43, 63, 63, 63, 65]","[Contain, Press, Press, Press, Press, Press]","[70, 68, 66, 65, 65, 65]","[Wide, Wide, Normal, Normal, Normal, Normal]","[Offside Trap, Cover, Cover, Cover, Cover, Cover]","[FC Barcelona, FC Barcelona, FC Barcelona, FC ..."
242,"[345, 346, 347, 348, 349, 350]","[9783, 9783, 9783, 9783, 9783, 9783]","[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[30, 56, 56, 56, 56, 53]","[Slow, Balanced, Balanced, Balanced, Balanced,...","[nan, nan, nan, nan, 55.0, 55.0]","[Little, Little, Little, Little, Normal, Normal]","[30, 42, 46, 46, 46, 47]","[Short, Mixed, Mixed, Mixed, Mixed, Mixed]","[Organised, Organised, Organised, Organised, O...",...,"[Normal, Normal, Lots, Lots, Lots, Normal]","[Organised, Organised, Organised, Organised, O...","[35, 38, 45, 45, 45, 45]","[Medium, Medium, Medium, Medium, Medium, Medium]","[35, 44, 50, 50, 50, 50]","[Press, Press, Press, Press, Press, Press]","[45, 69, 59, 59, 59, 59]","[Normal, Wide, Normal, Normal, Normal, Normal]","[Offside Trap, Cover, Cover, Cover, Cover, Off...","[RC Deportivo de La Coruña, RC Deportivo de La..."
243,"[1049, 1050, 1051, 1052, 1053, 1054]","[8633, 8633, 8633, 8633, 8633, 8633]","[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[55, 54, 45, 50, 50, 50]","[Balanced, Balanced, Balanced, Balanced, Balan...","[nan, nan, nan, nan, 54.0, 57.0]","[Little, Little, Little, Little, Normal, Normal]","[30, 39, 35, 41, 41, 46]","[Short, Mixed, Mixed, Mixed, Mixed, Mixed]","[Free Form, Free Form, Free Form, Organised, O...",...,"[Lots, Lots, Lots, Lots, Lots, Normal]","[Free Form, Free Form, Free Form, Free Form, F...","[65, 68, 49, 39, 39, 52]","[Medium, High, Medium, Medium, Medium, Medium]","[40, 55, 60, 49, 49, 60]","[Press, Press, Press, Press, Press, Press]","[65, 55, 68, 65, 65, 63]","[Normal, Normal, Wide, Normal, Normal, Normal]","[Offside Trap, Cover, Cover, Cover, Cover, Cover]","[Real Madrid CF, Real Madrid CF, Real Madrid C..."
244,"[1445, 1446, 1447, 1448, 1449, 1450]","[8394, 8394, 8394, 8394, 8394, 8394]","[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[30, 43, 34, 38, 38, 52]","[Slow, Balanced, Balanced, Balanced, Balanced,...","[nan, nan, nan, nan, 48.0, 52.0]","[Little, Little, Little, Little, Normal, Normal]","[30, 40, 23, 23, 35, 50]","[Short, Mixed, Short, Short, Mixed, Mixed]","[Free Form, Organised, Organised, Organised, O...",...,"[Lots, Normal, Normal, Normal, Normal, Normal]","[Organised, Organised, Organised, Organised, O...","[40, 38, 51, 51, 51, 48]","[Medium, Medium, Medium, Medium, Medium, Medium]","[30, 40, 46, 46, 46, 43]","[Contain, Press, Press, Press, Press, Press]","[45, 53, 61, 61, 61, 49]","[Normal, Normal, Normal, Normal, Normal, Normal]","[Offside Trap, Cover, Cover, Cover, Cover, Cover]","[Real Zaragoza, Real Zaragoza, Real Zaragoza, ..."
260,"[1261, 1262, 1263, 1264]","[9867, 9867, 9867, 9867]","[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[30, 56, 56, 56]","[Slow, Balanced, Balanced, Balanced]","[nan, nan, 50.0, 50.0]","[Little, Little, Normal, Normal]","[30, 51, 57, 57]","[Short, Mixed, Mixed, Mixed]","[Organised, Organised, Organised, Organised]",...,"[Normal, Normal, Normal, Normal]","[Organised, Organised, Organised, Organised]","[50, 57, 52, 52]","[Medium, Medium, Medium, Medium]","[30, 50, 50, 50]","[Contain, Press, Press, Press]","[45, 67, 65, 69]","[Normal, Wide, Normal, Wide]","[Cover, Cover, Cover, Cover]","[CD Tenerife, CD Tenerife, CD Tenerife, CD Ten..."
448,"[89, 90, 91, 92, 93, 94]","[8315, 8315, 8315, 8315, 8315, 8315]","[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[60, 70, 42, 46, 46, 46]","[Balanced, Fast, Balanced, Balanced, Balanced,...","[nan, nan, nan, nan, 41.0, 46.0]","[Little, Little, Little, Little, Normal, Normal]","[45, 69, 59, 38, 38, 39]","[Mixed, Long, Mixed, Mixed, Mixed, Mixed]","[Organised, Organised, Organised, Organised, O...",...,"[Normal, Normal, Normal, Normal, Normal, Normal]","[Organised, Organised, Organised, Free Form, O...","[30, 48, 37, 37, 37, 49]","[Deep, Medium, Medium, Medium, Medium, Medium]","[70, 67, 60, 60, 60, 57]","[Double, Double, Press, Press, Press, Press]","[35, 55, 68, 68, 65, 50]","[Normal, Normal, Wide, Wide, Normal, Normal]","[Cover, Cover, Cover, Cover, Cover, Cover]","[Athletic Club de Bilbao, Athletic Club de Bil..."
449,"[1043, 1044, 1045, 1046, 1047, 1048]","[8603, 8603, 8603, 8603, 8603, 8603]","[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[45, 37, 55, 59, 59, 59]","[Balanced, Balanced, Balanced, Balanced, Balan...","[nan, nan, nan, nan, 49.0, 49.0]","[Little, Little, Little, Little, Normal, Normal]","[45, 51, 37, 37, 37, 37]","[Mixed, Mixed, Mixed, Mixed, Mixed, Mixed]","[Organised, Organised, Organised, Organised, O...",...,"[Normal, Lots, Normal, Normal, Normal, Normal]","[Free Form, Free Form, Organised, Organised, O...","[50, 42, 58, 58, 58, 58]","[Medium, Medium, Medium, Medium, Medium, Medium]","[45, 40, 49, 49, 49, 49]","[Press, Press, Press, Press, Press, Press]","[55, 53, 58, 58, 58, 58]","[Normal, Normal, Normal, Normal, Normal, Normal]","[Offside Trap, Cover, Cover, Cover, Cover, Cover]","[Real Betis Balompié, Real Betis Balompié, Rea..."
450,"[283, 284, 285, 286, 287, 288]","[9910, 9910, 9910, 9910, 9910, 9910]","[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[35, 43, 53, 53, 53, 55]","[Balanced, Balanced, Balanced, Balanced, Balan...","[nan, nan, nan, nan, 54.0, 59.0]","[Little, Little, Little, Little, Normal, Normal]","[30, 44, 62, 62, 62, 38]","[Short, Mixed, Mixed, Mixed, Mixed, Mixed]","[Organised, Organised, Organised, Organised, O...",...,"[Lots, Normal, Normal, Normal, Normal, Normal]","[Organised, Organised, Organised, Free Form, O...","[35, 40, 42, 42, 42, 55]","[Medium, Medium, Medium, Medium, Medium, Medium]","[30, 41, 52, 52, 52, 55]","[Contain, Press, Press, Press, Press, Press]","[50, 47, 68, 68, 65, 59]","[Normal, Normal, Wide, Wide, Normal, Normal]","[Offside Trap, Cover, Cover, Cover, Cover, Cover]","[RC Celta de Vigo, RC Celta de Vigo, RC Celta ..."
452,"[395, 396, 397, 398, 399, 400]","[8558, 8558, 8558, 8558, 8558, 8558]","[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[55, 68, 46, 50, 50, 50]","[Balanced, Fast, Balanced, Balanced, Balanced,...","[nan, nan, nan, nan, 52.0, 52.0]","[Little, Little, Little, Little, Normal, Normal]","[40, 55, 44, 44, 44, 44]","[Mixed, Mixed, Mixed, Mixed, Mixed, Mixed]","[Organised, Organised, Organised, Organised, O...",...,"[Lots, Normal, Normal, Normal, Normal, Normal]","[Organised, Organised, Organised, Free Form, O...","[70, 51, 37, 37, 37, 37]","[High, Medium, Medium, Medium, Medium, Medium]","[50, 58, 40, 40, 40, 40]","[Press, Press, Press, Press, Press, Press]","[60, 56, 45, 45, 45, 45]","[Normal, Normal, Normal, Normal, Normal, Normal]","[Cover, Cover, Cover, Cover, Cover, Cover]","[RCD Espanyol, RCD Espanyol, RCD Espanyol, RCD..."
453,"[795, 796, 797, 798, 799, 800]","[8661, 8661, 8661, 8661, 8661, 8661]","[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[40, 53, 58, 62, 62, 62]","[Balanced, Balanced, Balanced, Balanced, Balan...","[nan, nan, nan, nan, 53.0, 53.0]","[Little, Little, Little, Little, Normal, Normal]","[40, 52, 57, 57, 57, 57]","[Mixed, Mixed, Mixed, Mixed, Mixed, Mixed]","[Organised, Organised, Organised, Organised, O...",...,"[Normal, Normal, Normal, Normal, Normal, Normal]","[Free Form, Free Form, Organised, Organised, O...","[45, 47, 59, 59, 59, 59]","[Medium, Medium, Medium, Medium, Medium, Medium]","[40, 48, 41, 41, 41, 41]","[Press, Press, Press, Press, Press, Press]","[45, 55, 56, 56, 56, 56]","[Normal, Normal, Normal, Normal, Normal, Normal]","[Offside Trap, Cover, Cover, Cover, Cover, Cover]","[RCD Mallorca, RCD Mallorca, RCD Mallorca, RCD..."
456,"[1020, 1021, 1022, 1023, 1024]","[8696, 8696, 8696, 8696, 8696]","[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[45, 53, 43, 47, 48]","[Balanced, Balanced, Balanced, Balanced, Balan...","[nan, nan, nan, nan, 52.0]","[Little, Little, Little, Little, Normal]","[55, 56, 44, 44, 47]","[Mixed, Mixed, Mixed, Mixed, Mixed]","[Organised, Organised, Organised, Organised, O...",...,"[Normal, Normal, Normal, Normal, Normal]","[Free Form, Organised, Organised, Organised, O...","[45, 47, 50, 50, 51]","[Medium, Medium, Medium, Medium, Medium]","[55, 37, 50, 50, 47]","[Press, Press, Press, Press, Press]","[50, 53, 68, 68, 53]","[Normal, Normal, Wide, Wide, Normal]","[Cover, Cover, Cover, Cover, Cover]","[Racing Santander, Racing Santander, Racing Sa..."
457,"[1055, 1056, 1057, 1058, 1059, 1060]","[8560, 8560, 8560, 8560, 8560, 8560]","[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[40, 54, 24, 28, 35, 60]","[Balanced, Balanced, Slow, Slow, Balanced, Bal...","[nan, nan, nan, nan, 52.0, 52.0]","[Little, Little, Little, Little, Normal, Normal]","[30, 43, 36, 36, 36, 50]","[Short, Mixed, Mixed, Mixed, Mixed, Mixed]","[Free Form, Organised, Organised, Organised, O...",...,"[Lots, Normal, Normal, Normal, Normal, Normal]","[Organised, Organised, Organised, Organised, O...","[45, 49, 48, 48, 48, 49]","[Medium, Medium, Medium, Medium, Medium, Medium]","[30, 49, 53, 53, 53, 53]","[Contain, Press, Press, Press, Press, Press]","[35, 51, 70, 70, 65, 53]","[Normal, Normal, Wide, Wide, Normal, Normal]","[Offside Trap, Cover, Cover, Cover, Cover, Cover]","[Real Sociedad, Real Sociedad, Real Sociedad, ..."
459,"[1199, 1200, 1201, 1202, 1203, 1204]","[9869, 9869, 9869, 9869, 9869, 9869]","[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[70, 68, 51, 55, 55, 55]","[Fast, Fast, Balanced, Balanced, Balanced, Bal...","[nan, nan, nan, nan, 48.0, 48.0]","[Little, Little, Little, Little, Normal, Normal]","[55, 53, 43, 43, 43, 50]","[Mixed, Mixed, Mixed, Mixed, Mixed, Mixed]","[Organised, Organised, Organised, Organised, O...",...,"[Lots, Normal, Normal, Normal, Normal, Normal]","[Organised, Organised, Organised, Organised, O...","[70, 58, 36, 36, 36, 45]","[High, Medium, Medium, Medium, Medium, Medium]","[70, 51, 60, 60, 60, 54]","[Double, Press, Press, Press, Press, Press]","[55, 55, 39, 39, 39, 41]","[Normal, Normal, Normal, Normal, Normal, Normal]","[Cover, Cover, Cover, Cover, Cover, Cover]","[Real Sporting de Gijón, Real Sporting de Gijó..."
461,"[1308, 1309, 1310, 1311, 1312, 1313]","[10267, 10267, 10267, 10267, 10267, 10267]","[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[30, 41, 20, 20, 30, 35]","[Slow, Balanced, Slow, Slow, Slow, Balanced]","[nan, nan, nan, nan, 45.0, 46.0]","[Little, Little, Little, Little, Normal, Normal]","[30, 40, 35, 35, 35, 35]","[Short, Mixed, Mixed, Mixed, Mixed, Mixed]","[Free Form, Organised, Organised, Organised, O...",...,"[Lots, Normal, Normal, Normal, Normal, Normal]","[Organised, Free Form, Organised, Organised, O...","[55, 40, 51, 51, 51, 49]","[Medium, Medium, Medium, Medium, Medium, Medium]","[60, 48, 38, 38, 38, 45]","[Press, Press, Press, Press, Press, Press]","[60, 54, 59, 59, 59, 53]","[Normal, Normal, Normal, Normal, Normal, Normal]","[Offside Trap, Cover, Cover, Cover, Cover, Cover]","[Valencia CF, Valencia CF, Valencia CF, Valenc..."
462,"[1320, 1321, 1322, 1323, 1324, 1325]","[10281, 10281, 10281, 10281, 10281, 10281]","[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[55, 54, 55, 55, 55, 43]","[Balanced, Balanced, Balanced, Balanced, Balan...","[nan, nan, nan, nan, 44.0, 40.0]","[Little, Little, Little, Little, Normal, Normal]","[40, 55, 54, 54, 54, 65]","[Mixed, Mixed, Mixed, Mixed, Mixed, Mixed]","[Organised, Organised, Organised, Organised, O...",...,"[Normal, Normal, Normal, Normal, Normal, Normal]","[Organised, Organised, Organised, Organised, O...","[30, 43, 51, 51, 51, 47]","[Deep, Medium, Medium, Medium, Medium, Medium]","[65, 52, 50, 50, 50, 40]","[Press, Press, Press, Press, Press, Press]","[30, 59, 60, 60, 60, 47]","[Narrow, Normal, Normal, Normal, Normal, Normal]","[Cover, Cover, Cover, Cover, Cover, Cover]","[Real Valladolid, Real Valladolid, Real Vallad..."
467,"[366, 367]","[8372, 8372]","[2014-09-19 00:00:00, 2015-09-10 00:00:00]","[62, 62]","[Balanced, Balanced]","[51.0, 51.0]","[Normal, Normal]","[52, 52]","[Mixed, Mixed]","[Organised, Organised]",...,"[Normal, Normal]","[Organised, Organised]","[37, 37]","[Medium, Medium]","[56, 56]","[Press, Press]","[49, 49]","[Normal, Normal]","[Cover, Cover]","[SD Eibar, SD Eibar]"
468,"[378, 379, 380, 381, 382, 383]","[10268, 10268, 10268, 10268, 10268, 10268]","[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[30, 43, 55, 55, 55, 51]","[Slow, Balanced, Balanced, Balanced, Balanced,...","[nan, nan, nan, nan, 47.0, 52.0]","[Little, Little, Little, Little, Normal, Normal]","[30, 39, 73, 73, 69, 48]","[Short, Mixed, Long, Long, Long, Mixed]","[Organised, Organised, Organised, Organised, O...",...,"[Lots, Normal, Normal, Normal, Normal, Normal]","[Organised, Organised, Organised, Organised, O...","[50, 40, 49, 49, 49, 49]","[Medium, Medium, Medium, Medium, Medium, Medium]","[45, 39, 51, 51, 51, 51]","[Press, Press, Press, Press, Press, Press]","[45, 51, 58, 58, 58, 58]","[Normal, Normal, Normal, Normal, Normal, Normal]","[Cover, Cover, Cover, Cover, Cover, Cover]","[Elche CF, Elche CF, Elche CF, Elche CF, Elche..."
472,"[666, 667, 668, 669, 670, 671]","[8306, 8306, 8306, 8306, 8306, 8306]","[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[30, 54, 48, 48, 48, 48]","[Slow, Balanced, Balanced, Balanced, Balanced,...","[nan, nan, nan, nan, 55.0, 55.0]","[Little, Little, Little, Little, Normal, Normal]","[30, 56, 44, 44, 44, 44]","[Short, Mixed, Mixed, Mixed, Mixed, Mixed]","[Organised, Organised, Organised, Organised, O...",...,"[Lots, Normal, Normal, Normal, Normal, Normal]","[Organised, Organised, Organised, Organised, O...","[35, 48, 53, 53, 53, 53]","[Medium, Medium, Medium, Medium, Medium, Medium]","[45, 56, 39, 39, 39, 39]","[Press, Press, Press, Press, Press, Press]","[45, 67, 57, 57, 57, 57]","[Normal, Wide, Normal, Normal, Normal, Normal]","[Offside Trap, Cover, Cover, Cover, Cover, Cover]","[UD Las Palmas, UD Las Palmas, UD Las Palmas, ..."
477,"[921, 922, 923, 924, 925, 926]","[8388, 8388, 8388, 8388, 8388, 8388]","[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[55, 71, 44, 44, 44, 44]","[Balanced, Fast, Balanced, Balanced, Balanced,...","[nan, nan, nan, nan, 48.0, 48.0]","[Little, Little, Little, Little, Normal, Normal]","[40, 53, 45, 45, 45, 45]","[Mixed, Mixed, Mixed, Mixed, Mixed, Mixed]","[Organised, Organised, Organised, Organised, O...",...,"[Normal, Normal, Normal, Normal, Normal, Normal]","[Organised, Organised, Organised, Organised, O...","[30, 40, 50, 50, 50, 50]","[Deep, Medium, Medium, Medium, Medium, Medium]","[55, 49, 46, 46, 46, 46]","[Press, Press, Press, Press, Press, Press]","[55, 55, 62, 62, 62, 62]","[Normal, Normal, Normal, Normal, Normal, Normal]","[Offside Trap, Cover, Cover, Cover, Cover, Cover]","[CD Numancia, CD Numancia, CD Numancia, CD Num..."
479,"[935, 936, 937, 938, 939, 940]","[8371, 8371, 8371, 8371, 8371, 8371]","[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[35, 55, 34, 38, 38, 38]","[Balanced, Balanced, Balanced, Balanced, Balan...","[nan, nan, nan, nan, 53.0, 53.0]","[Little, Little, Little, Little, Normal, Normal]","[35, 54, 52, 52, 52, 52]","[Mixed, Mixed, Mixed, Mixed, Mixed, Mixed]","[Organised, Organised, Organised, Organised, O...",...,"[Normal, Lots, Normal, Normal, Normal, Normal]","[Free Form, Free Form, Organised, Organised, O...","[30, 48, 47, 47, 47, 47]","[Deep, Medium, Medium, Medium, Medium, Medium]","[65, 61, 52, 52, 52, 52]","[Press, Press, Press, Press, Press, Press]","[55, 68, 69, 69, 65, 69]","[Normal, Wide, Wide, Wide, Normal, Wide]","[Cover, Cover, Cover, Cover, Cover, Cover]","[CA Osasuna, CA Osasuna, CA Osasuna, CA Osasun..."
480,"[1031, 1032, 1033, 1034, 1035, 1036]","[8370, 8370, 8370, 8370, 8370, 8370]","[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[40, 53, 41, 45, 45, 29]","[Balanced, Balanced, Balanced, Balanced, Balan...","[nan, nan, nan, nan, 52.0, 52.0]","[Little, Little, Little, Little, Normal, Normal]","[30, 55, 44, 44, 44, 44]","[Short, Mixed, Mixed, Mixed, Mixed, Mixed]","[Organised, Organised, Organised, Free Form, O...",...,"[Lots, Normal, Normal, Normal, Normal, Normal]","[Organised, Organised, Organised, Organised, O...","[30, 58, 63, 63, 63, 54]","[Deep, Medium, Medium, Medium, Medium, Medium]","[50, 52, 51, 51, 51, 52]","[Press, Press, Press, Press, Press, Press]","[40, 68, 59, 59, 59, 63]","[Normal, Wide, Normal, Normal, Normal, Normal]","[Offside Trap, Cover, Cover, Cover, Cover, Cover]","[Rayo Vallecano, Rayo Vallecano, Rayo Vallecan..."
481,"[1157, 1158, 1159, 1160, 1161, 1162]","[8302, 8302, 8302, 8302, 8302, 8302]","[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[30, 68, 61, 65, 65, 53]","[Slow, Fast, Balanced, Balanced, Balanced, Bal...","[nan, nan, nan, nan, 53.0, 53.0]","[Little, Little, Little, Little, Normal, Normal]","[30, 58, 65, 65, 65, 53]","[Short, Mixed, Mixed, Mixed, Mixed, Mixed]","[Free Form, Free Form, Organised, Organised, O...",...,"[Lots, Lots, Normal, Normal, Normal, Normal]","[Free Form, Free Form, Organised, Organised, O...","[60, 57, 38, 38, 38, 42]","[Medium, Medium, Medium, Medium, Medium, Medium]","[70, 58, 49, 49, 49, 48]","[Double, Press, Press, Press, Press, Press]","[65, 68, 55, 55, 55, 59]","[Normal, Wide, Normal, Normal, Normal, Normal]","[Offside Trap, Cover, Cover, Cover, Cover, Cover]","[Sevilla FC, Sevilla FC, Sevilla FC, Sevilla F..."

In [116]:
df_grb['team_api_id'] = df_grb['team_api_id'].apply(lambda x: x[0])
df_grb['team_long_name'] = df_grb['team_long_name'].apply(lambda x: x[0])
df_grb

,id,team_api_id,date,buildUpPlaySpeed,buildUpPlaySpeedClass,buildUpPlayDribbling,buildUpPlayDribblingClass,buildUpPlayPassing,buildUpPlayPassingClass,buildUpPlayPositioningClass,...,chanceCreationShootingClass,chanceCreationPositioningClass,defencePressure,defencePressureClass,defenceAggression,defenceAggressionClass,defenceTeamWidth,defenceTeamWidthClass,defenceDefenderLineClass,team_long_name
team_fifa_api_id,,,,,,,,,,,,,,,,,,,,,
240,"[95, 96, 97, 98, 99, 100]",9906,"[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[64, 57, 47, 47, 47, 57]","[Balanced, Balanced, Balanced, Balanced, Balan...","[nan, nan, nan, nan, 52.0, 50.0]","[Little, Little, Little, Little, Normal, Normal]","[30, 54, 51, 51, 51, 50]","[Short, Mixed, Mixed, Mixed, Mixed, Mixed]","[Free Form, Organised, Organised, Organised, O...",...,"[Lots, Lots, Normal, Normal, Normal, Normal]","[Free Form, Organised, Organised, Organised, O...","[70, 58, 52, 52, 52, 49]","[High, Medium, Medium, Medium, Medium, Medium]","[34, 48, 37, 37, 37, 42]","[Press, Press, Press, Press, Press, Press]","[55, 54, 55, 55, 55, 52]","[Normal, Normal, Normal, Normal, Normal, Normal]","[Offside Trap, Cover, Cover, Cover, Cover, Cover]",Atlético Madrid
241,"[119, 120, 121, 122, 123, 124]",8634,"[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[42, 43, 24, 35, 35, 36]","[Balanced, Balanced, Slow, Balanced, Balanced,...","[nan, nan, nan, nan, 35.0, 35.0]","[Little, Little, Little, Little, Normal, Normal]","[30, 34, 25, 32, 32, 51]","[Short, Mixed, Short, Short, Short, Mixed]","[Free Form, Free Form, Free Form, Free Form, F...",...,"[Lots, Lots, Normal, Normal, Normal, Normal]","[Free Form, Free Form, Free Form, Free Form, F...","[70, 67, 66, 61, 61, 61]","[High, High, Medium, Medium, Medium, Medium]","[30, 43, 63, 63, 63, 65]","[Contain, Press, Press, Press, Press, Press]","[70, 68, 66, 65, 65, 65]","[Wide, Wide, Normal, Normal, Normal, Normal]","[Offside Trap, Cover, Cover, Cover, Cover, Cover]",FC Barcelona
242,"[345, 346, 347, 348, 349, 350]",9783,"[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[30, 56, 56, 56, 56, 53]","[Slow, Balanced, Balanced, Balanced, Balanced,...","[nan, nan, nan, nan, 55.0, 55.0]","[Little, Little, Little, Little, Normal, Normal]","[30, 42, 46, 46, 46, 47]","[Short, Mixed, Mixed, Mixed, Mixed, Mixed]","[Organised, Organised, Organised, Organised, O...",...,"[Normal, Normal, Lots, Lots, Lots, Normal]","[Organised, Organised, Organised, Organised, O...","[35, 38, 45, 45, 45, 45]","[Medium, Medium, Medium, Medium, Medium, Medium]","[35, 44, 50, 50, 50, 50]","[Press, Press, Press, Press, Press, Press]","[45, 69, 59, 59, 59, 59]","[Normal, Wide, Normal, Normal, Normal, Normal]","[Offside Trap, Cover, Cover, Cover, Cover, Off...",RC Deportivo de La Coruña
243,"[1049, 1050, 1051, 1052, 1053, 1054]",8633,"[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[55, 54, 45, 50, 50, 50]","[Balanced, Balanced, Balanced, Balanced, Balan...","[nan, nan, nan, nan, 54.0, 57.0]","[Little, Little, Little, Little, Normal, Normal]","[30, 39, 35, 41, 41, 46]","[Short, Mixed, Mixed, Mixed, Mixed, Mixed]","[Free Form, Free Form, Free Form, Organised, O...",...,"[Lots, Lots, Lots, Lots, Lots, Normal]","[Free Form, Free Form, Free Form, Free Form, F...","[65, 68, 49, 39, 39, 52]","[Medium, High, Medium, Medium, Medium, Medium]","[40, 55, 60, 49, 49, 60]","[Press, Press, Press, Press, Press, Press]","[65, 55, 68, 65, 65, 63]","[Normal, Normal, Wide, Normal, Normal, Normal]","[Offside Trap, Cover, Cover, Cover, Cover, Cover]",Real Madrid CF
244,"[1445, 1446, 1447, 1448, 1449, 1450]",8394,"[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[30, 43, 34, 38, 38, 52]","[Slow, Balanced, Balanced, Balanced, Balanced,...","[nan, nan, nan, nan, 48.0, 52.0]","[Little, Little, Little, Little, Normal, Normal]","[30, 40, 23, 23, 35, 50]","[Short, Mixed, Short, Short, Mixed, Mixed]","[Free Form, Organised, Organised, Organised, O...",...,"[Lots, Normal, Normal, Normal, Normal, Normal]","[Organised, Organised, Organised, Organised, O...","[40, 38, 51, 51, 51, 48]","[Medium, Medium, Medium, Medium, Medium, Medium]","[30, 40, 46, 46, 46, 43]","[Contain, Press, Press, Press, Press, Press]","[45, 53, 61, 61, 61, 49]","[Normal, Normal, Normal, Normal, Normal, Normal]","[Offside Trap, Cover, Cover, Cover, Cover, Cover]",Real Zaragoza
260,"[1261, 1262, 1263, 1264]",9867,"[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[30, 56, 56, 56]","[Slow, Balanced, Balanced, Balanced]","[nan, nan, 50.0, 50.0]","[Little, Little, Normal, Normal]","[30, 51, 57, 57]","[Short, Mixed, Mixed, Mixed]","[Organised, Organised, Organised, Organised]",...,"[Normal, Normal, Normal, Normal]","[Organised, Organised, Organised, Organised]","[50, 57, 52, 52]","[Medium, Medium, Medium, Medium]","[30, 50, 50, 50]","[Contain, Press, Press, Press]","[45, 67, 65, 69]","[Normal, Wide, Normal, Wide]","[Cover, Cover, Cover, Cover]",CD Tenerife
448,"[89, 90, 91, 92, 93, 94]",8315,"[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[60, 70, 42, 46, 46, 46]","[Balanced, Fast, Balanced, Balanced, Balanced,...","[nan, nan, nan, nan, 41.0, 46.0]","[Little, Little, Little, Little, Normal, Normal]","[45, 69, 59, 38, 38, 39]","[Mixed, Long, Mixed, Mixed, Mixed, Mixed]","[Organised, Organised, Organised, Organised, O...",...,"[Normal, Normal, Normal, Normal, Normal, Normal]","[Organised, Organised, Organised, Free Form, O...","[30, 48, 37, 37, 37, 49]","[Deep, Medium, Medium, Medium, Medium, Medium]","[70, 67, 60, 60, 60, 57]","[Double, Double, Press, Press, Press, Press]","[35, 55, 68, 68, 65, 50]","[Normal, Normal, Wide, Wide, Normal, Normal]","[Cover, Cover, Cover, Cover, Cover, Cover]",Athletic Club de Bilbao
449,"[1043, 1044, 1045, 1046, 1047, 1048]",8603,"[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[45, 37, 55, 59, 59, 59]","[Balanced, Balanced, Balanced, Balanced, Balan...","[nan, nan, nan, nan, 49.0, 49.0]","[Little, Little, Little, Little, Normal, Normal]","[45, 51, 37, 37, 37, 37]","[Mixed, Mixed, Mixed, Mixed, Mixed, Mixed]","[Organised, Organised, Organised, Organised, O...",...,"[Normal, Lots, Normal, Normal, Normal, Normal]","[Free Form, Free Form, Organised, Organised, O...","[50, 42, 58, 58, 58, 58]","[Medium, Medium, Medium, Medium, Medium, Medium]","[45, 40, 49, 49, 49, 49]","[Press, Press, Press, Press, Press, Press]","[55, 53, 58, 58, 58, 58]","[Normal, Normal, Normal, Normal, Normal, Normal]","[Offside Trap, Cover, Cover, Cover, Cover, Cover]",Real Betis Balompié
450,"[283, 284, 285, 286, 287, 288]",9910,"[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[35, 43, 53, 53, 53, 55]","[Balanced, Balanced, Balanced, Balanced, Balan...","[nan, nan, nan, nan, 54.0, 59.0]","[Little, Little, Little, Little, Normal, Normal]","[30, 44, 62, 62, 62, 38]","[Short, Mixed, Mixed, Mixed, Mixed, Mixed]","[Organised, Organised, Organised, Organised, O...",...,"[Lots, Normal, Normal, Normal, Normal, Normal]","[Organised, Organised, Organised, Free Form, O...","[35, 40, 42, 42, 42, 55]","[Medium, Medium, Medium, Medium, Medium, Medium]","[30, 41, 52, 52, 52, 55]","[Contain, Press, Press, Press, Press, Press]","[50, 47, 68, 68, 65, 59]","[Normal, Normal, Wide, Wide, Normal, Normal]","[Offside Trap, Cover, Cover, Cover, Cover, Cover]",RC Celta de Vigo
452,"[395, 396, 397, 398, 399, 400]",8558,"[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[55, 68, 46, 50, 50, 50]","[Balanced, Fast, Balanced, Balanced, Balanced,...","[nan, nan, nan, nan, 52.0, 52.0]","[Little, Little, Little, Little, Normal, Normal]","[40, 55, 44, 44, 44, 44]","[Mixed, Mixed, Mixed, Mixed, Mixed, Mixed]","[Organised, Organised, Organised, Organised, O...",...,"[Lots, Normal, Normal, Normal, Normal, Normal]","[Organised, Organised, Organised, Free Form, O...","[70, 51, 37, 37, 37, 37]","[High, Medium, Medium, Medium, Medium, Medium]","[50, 58, 40, 40, 40, 40]","[Press, Press, Press, Press, Press, Press]","[60, 56, 45, 45, 45, 45]","[Normal, Normal, Normal, Normal, Normal, Normal]","[Cover, Cover, Cover, Cover, Cover, Cover]",RCD Espanyol
453,"[795, 796, 797, 798, 799, 800]",8661,"[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[40, 53, 58, 62, 62, 62]","[Balanced, Balanced, Balanced, Balanced, Balan...","[nan, nan, nan, nan, 53.0, 53.0]","[Little, Little, Little, Little, Normal, Normal]","[40, 52, 57, 57, 57, 57]","[Mixed, Mixed, Mixed, Mixed, Mixed, Mixed]","[Organised, Organised, Organised, Organised, O...",...,"[Normal, Normal, Normal, Normal, Normal, Normal]","[Free Form, Free Form, Organised, Organised, O...","[45, 47, 59, 59, 59, 59]","[Medium, Medium, Medium, Medium, Medium, Medium]","[40, 48, 41, 41, 41, 41]","[Press, Press, Press, Press, Press, Press]","[45, 55, 56, 56, 56, 56]","[Normal, Normal, Normal, Normal, Normal, Normal]","[Offside Trap, Cover, Cover, Cover, Cover, Cover]",RCD Mallorca
456,"[1020, 1021, 1022, 1023, 1024]",8696,"[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[45, 53, 43, 47, 48]","[Balanced, Balanced, Balanced, Balanced, Balan...","[nan, nan, nan, nan, 52.0]","[Little, Little, Little, Little, Normal]","[55, 56, 44, 44, 47]","[Mixed, Mixed, Mixed, Mixed, Mixed]","[Organised, Organised, Organised, Organised, O...",...,"[Normal, Normal, Normal, Normal, Normal]","[Free Form, Organised, Organised, Organised, O...","[45, 47, 50, 50, 51]","[Medium, Medium, Medium, Medium, Medium]","[55, 37, 50, 50, 47]","[Press, Press, Press, Press, Press]","[50, 53, 68, 68, 53]","[Normal, Normal, Wide, Wide, Normal]","[Cover, Cover, Cover, Cover, Cover]",Racing Santander
457,"[1055, 1056, 1057, 1058, 1059, 1060]",8560,"[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[40, 54, 24, 28, 35, 60]","[Balanced, Balanced, Slow, Slow, Balanced, Bal...","[nan, nan, nan, nan, 52.0, 52.0]","[Little, Little, Little, Little, Normal, Normal]","[30, 43, 36, 36, 36, 50]","[Short, Mixed, Mixed, Mixed, Mixed, Mixed]","[Free Form, Organised, Organised, Organised, O...",...,"[Lots, Normal, Normal, Normal, Normal, Normal]","[Organised, Organised, Organised, Organised, O...","[45, 49, 48, 48, 48, 49]","[Medium, Medium, Medium, Medium, Medium, Medium]","[30, 49, 53, 53, 53, 53]","[Contain, Press, Press, Press, Press, Press]","[35, 51, 70, 70, 65, 53]","[Normal, Normal, Wide, Wide, Normal, Normal]","[Offside Trap, Cover, Cover, Cover, Cover, Cover]",Real Sociedad
459,"[1199, 1200, 1201, 1202, 1203, 1204]",9869,"[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[70, 68, 51, 55, 55, 55]","[Fast, Fast, Balanced, Balanced, Balanced, Bal...","[nan, nan, nan, nan, 48.0, 48.0]","[Little, Little, Little, Little, Normal, Normal]","[55, 53, 43, 43, 43, 50]","[Mixed, Mixed, Mixed, Mixed, Mixed, Mixed]","[Organised, Organised, Organised, Organised, O...",...,"[Lots, Normal, Normal, Normal, Normal, Normal]","[Organised, Organised, Organised, Organised, O...","[70, 58, 36, 36, 36, 45]","[High, Medium, Medium, Medium, Medium, Medium]","[70, 51, 60, 60, 60, 54]","[Double, Press, Press, Press, Press, Press]","[55, 55, 39, 39, 39, 41]","[Normal, Normal, Normal, Normal, Normal, Normal]","[Cover, Cover, Cover, Cover, Cover, Cover]",Real Sporting de Gijón
461,"[1308, 1309, 1310, 1311, 1312, 1313]",10267,"[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[30, 41, 20, 20, 30, 35]","[Slow, Balanced, Slow, Slow, Slow, Balanced]","[nan, nan, nan, nan, 45.0, 46.0]","[Little, Little, Little, Little, Normal, Normal]","[30, 40, 35, 35, 35, 35]","[Short, Mixed, Mixed, Mixed, Mixed, Mixed]","[Free Form, Organised, Organised, Organised, O...",...,"[Lots, Normal, Normal, Normal, Normal, Normal]","[Organised, Free Form, Organised, Organised, O...","[55, 40, 51, 51, 51, 49]","[Medium, Medium, Medium, Medium, Medium, Medium]","[60, 48, 38, 38, 38, 45]","[Press, Press, Press, Press, Press, Press]","[60, 54, 59, 59, 59, 53]","[Normal, Normal, Normal, Normal, Normal, Normal]","[Offside Trap, Cover, Cover, Cover, Cover, Cover]",Valencia CF
462,"[1320, 1321, 1322, 1323, 1324, 1325]",10281,"[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[55, 54, 55, 55, 55, 43]","[Balanced, Balanced, Balanced, Balanced, Balan...","[nan, nan, nan, nan, 44.0, 40.0]","[Little, Little, Little, Little, Normal, Normal]","[40, 55, 54, 54, 54, 65]","[Mixed, Mixed, Mixed, Mixed, Mixed, Mixed]","[Organised, Organised, Organised, Organised, O...",...,"[Normal, Normal, Normal, Normal, Normal, Normal]","[Organised, Organised, Organised, Organised, O...","[30, 43, 51, 51, 51, 47]","[Deep, Medium, Medium, Medium, Medium, Medium]","[65, 52, 50, 50, 50, 40]","[Press, Press, Press, Press, Press, Press]","[30, 59, 60, 60, 60, 47]","[Narrow, Normal, Normal, Normal, Normal, Normal]","[Cover, Cover, Cover, Cover, Cover, Cover]",Real Valladolid
467,"[366, 367]",8372,"[2014-09-19 00:00:00, 2015-09-10 00:00:00]","[62, 62]","[Balanced, Balanced]","[51.0, 51.0]","[Normal, Normal]","[52, 52]","[Mixed, Mixed]","[Organised, Organised]",...,"[Normal, Normal]","[Organised, Organised]","[37, 37]","[Medium, Medium]","[56, 56]","[Press, Press]","[49, 49]","[Normal, Normal]","[Cover, Cover]",SD Eibar
468,"[378, 379, 380, 381, 382, 383]",10268,"[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[30, 43, 55, 55, 55, 51]","[Slow, Balanced, Balanced, Balanced, Balanced,...","[nan, nan, nan, nan, 47.0, 52.0]","[Little, Little, Little, Little, Normal, Normal]","[30, 39, 73, 73, 69, 48]","[Short, Mixed, Long, Long, Long, Mixed]","[Organised, Organised, Organised, Organised, O...",...,"[Lots, Normal, Normal, Normal, Normal, Normal]","[Organised, Organised, Organised, Organised, O...","[50, 40, 49, 49, 49, 49]","[Medium, Medium, Medium, Medium, Medium, Medium]","[45, 39, 51, 51, 51, 51]","[Press, Press, Press, Press, Press, Press]","[45, 51, 58, 58, 58, 58]","[Normal, Normal, Normal, Normal, Normal, Normal]","[Cover, Cover, Cover, Cover, Cover, Cover]",Elche CF
472,"[666, 667, 668, 669, 670, 671]",8306,"[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[30, 54, 48, 48, 48, 48]","[Slow, Balanced, Balanced, Balanced, Balanced,...","[nan, nan, nan, nan, 55.0, 55.0]","[Little, Little, Little, Little, Normal, Normal]","[30, 56, 44, 44, 44, 44]","[Short, Mixed, Mixed, Mixed, Mixed, Mixed]","[Organised, Organised, Organised, Organised, O...",...,"[Lots, Normal, Normal, Normal, Normal, Normal]","[Organised, Organised, Organised, Organised, O...","[35, 48, 53, 53, 53, 53]","[Medium, Medium, Medium, Medium, Medium, Medium]","[45, 56, 39, 39, 39, 39]","[Press, Press, Press, Press, Press, Press]","[45, 67, 57, 57, 57, 57]","[Normal, Wide, Normal, Normal, Normal, Normal]","[Offside Trap, Cover, Cover, Cover, Cover, Cover]",UD Las Palmas
477,"[921, 922, 923, 924, 925, 926]",8388,"[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[55, 71, 44, 44, 44, 44]","[Balanced, Fast, Balanced, Balanced, Balanced,...","[nan, nan, nan, nan, 48.0, 48.0]","[Little, Little, Little, Little, Normal, Normal]","[40, 53, 45, 45, 45, 45]","[Mixed, Mixed, Mixed, Mixed, Mixed, Mixed]","[Organised, Organised, Organised, Organised, O...",...,"[Normal, Normal, Normal, Normal, Normal, Normal]","[Organised, Organised, Organised, Organised, O...","[30, 40, 50, 50, 50, 50]","[Deep, Medium, Medium, Medium, Medium, Medium]","[55, 49, 46, 46, 46, 46]","[Press, Press, Press, Press, Press, Press]","[55, 55, 62, 62, 62, 62]","[Normal, Normal, Normal, Normal, Normal, Normal]","[Offside Trap, Cover, Cover, Cover, Cover, Cover]",CD Numancia
479,"[935, 936, 937, 938, 939, 940]",8371,"[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[35, 55, 34, 38, 38, 38]","[Balanced, Balanced, Balanced, Balanced, Balan...","[nan, nan, nan, nan, 53.0, 53.0]","[Little, Little, Little, Little, Normal, Normal]","[35, 54, 52, 52, 52, 52]","[Mixed, Mixed, Mixed, Mixed, Mixed, Mixed]","[Organised, Organised, Organised, Organised, O...",...,"[Normal, Lots, Normal, Normal, Normal, Normal]","[Free Form, Free Form, Organised, Organised, O...","[30, 48, 47, 47, 47, 47]","[Deep, Medium, Medium, Medium, Medium, Medium]","[65, 61, 52, 52, 52, 52]","[Press, Press, Press, Press, Press, Press]","[55, 68, 69, 69, 65, 69]","[Normal, Wide, Wide, Wide, Normal, Wide]","[Cover, Cover, Cover, Cover, Cover, Cover]",CA Osasuna
480,"[1031, 1032, 1033, 1034, 1035, 1036]",8370,"[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[40, 53, 41, 45, 45, 29]","[Balanced, Balanced, Balanced, Balanced, Balan...","[nan, nan, nan, nan, 52.0, 52.0]","[Little, Little, Little, Little, Normal, Normal]","[30, 55, 44, 44, 44, 44]","[Short, Mixed, Mixed, Mixed, Mixed, Mixed]","[Organised, Organised, Organised, Free Form, O...",...,"[Lots, Normal, Normal, Normal, Normal, Normal]","[Organised, Organised, Organised, Organised, O...","[30, 58, 63, 63, 63, 54]","[Deep, Medium, Medium, Medium, Medium, Medium]","[50, 52, 51, 51, 51, 52]","[Press, Press, Press, Press, Press, Press]","[40, 68, 59, 59, 59, 63]","[Normal, Wide, Normal, Normal, Normal, Normal]","[Offside Trap, Cover, Cover, Cover, Cover, Cover]",Rayo Vallecano
481,"[1157, 1158, 1159, 1160, 1161, 1162]",8302,"[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[30, 68, 61, 65, 65, 53]","[Slow, Fast, Balanced, Balanced, Balanced, Bal...","[nan, nan, nan, nan, 53.0, 53.0]","[Little, Little, Little, Little, Normal, Normal]","[30, 58, 65, 65, 65, 53]","[Short, Mixed, Mixed, Mixed, Mixed, Mixed]","[Free Form, Free Form, Organised, Organised, O...",...,"[Lots, Lots, Normal, Normal, Normal, Normal]","[Free Form, Free Form, Organised, Organised, O...","[60, 57, 38, 38, 38, 42]","[Medium, Medium, Medium, Medium, Medium, Medium]","[70, 58, 49, 49, 49, 48]","[Double, Press, Press, Press, Press, Press]","[65, 68, 55, 55, 55, 59]","[Normal, Wide, Normal, Normal, Normal, Normal]","[Offside Trap, Cover, Cover, Cover, Cover, Cover]",Sevilla FC
483,"[1336, 1337, 1338, 1339, 1340, 1341]",10205,"[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[64, 42, 20, 24, 35, 48]","[Balanced, Balanced, Slow, Slow, Balanced, Bal...","[nan, nan, nan, nan, 42.0, 42.0]","[Little, Little, Little, Little, Normal, Normal]","[30, 41, 26, 26, 35, 36]","[Short, Mixed, Short, Short, Mixed, Mixed]","[Free Form, Free Form, Organised, Organised, O...",...,"[Lots, Lots, Normal, Normal, Normal, Normal]","[Free Form, Free Form, Organised, Organised, O...","[65, 50, 51, 51, 51, 47]","[Medium, Medium, Medium, Medium, Medium, Medium]","[30, 48, 51, 51, 51, 48]","[Contain, Press, Press, Press, Press, Press]","[70, 54, 56, 56, 56, 44]","[Wide, Normal, Normal, Normal, Normal, Normal]","[Offside Trap, Cover, Cover, Cover, Cover, Cover]",Villarreal CF
571,"[1061, 1062, 1063, 1064, 1065, 1066]",8479,"[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[50, 45, 41, 41, 41, 37]","[Balanced, Balanced, Balanced, Balanced, Balan...","[nan, nan, nan, nan, 53.0, 38.0]","[Little, Little, Little, Little, Normal, Normal]","[40, 58, 54, 54, 54, 43]","[Mixed, Mixed, Mixed, Mixed, Mixed, Mixed]","[Organised, Organised, Organised, Organised, O...",...,"[Normal, Normal, Little, Little, Normal, Normal]","[Organised, Organised, Organised, Organised, O...","[35, 39, 40, 40, 40, 40]","[Medium, Medium, Medium, Medium, Medium, Medium]","[55, 39, 49, 49, 49, 49]","[Press, Press, Press, Press, Press, Press]","[40, 66, 62, 62, 62, 54]","[Normal, Normal, Normal, Normal, Normal, Normal]","[Cover, Cover, Cover, Cover, Cover, Cover]",RC Recreativo

In [118]:
s = df_grb['team_long_name']
s

team_fifa_api_id
240                 Atlético Madrid
241                    FC Barcelona
242       RC Deportivo de La Coruña
243                  Real Madrid CF
244                   Real Zaragoza
260                     CD Tenerife
448         Athletic Club de Bilbao
449             Real Betis Balompié
450                RC Celta de Vigo
452                    RCD Espanyol
453                    RCD Mallorca
456                Racing Santander
457                   Real Sociedad
459          Real Sporting de Gijón
461                     Valencia CF
462                 Real Valladolid
467                        SD Eibar
468                        Elche CF
472                   UD Las Palmas
477                     CD Numancia
479                      CA Osasuna
480                  Rayo Vallecano
481                      Sevilla FC
483                   Villarreal CF
571                   RC Recreativo
573                       Málaga CF
1742           Xerez Club Deportivo
1853                     Levante UD
1860                      Getafe CF
1861                     UD Almería
1867                     Córdoba CF
100879      Hércules Club de Fútbol
110832                   Granada CF
Name: team_long_name, dtype: object

In [122]:
df_grb = df_grb.drop(columns = ['team_long_name'])
df_grb.insert(0,'team_long_name', s)
df_grb

,team_long_name,id,team_api_id,date,buildUpPlaySpeed,buildUpPlaySpeedClass,buildUpPlayDribbling,buildUpPlayDribblingClass,buildUpPlayPassing,buildUpPlayPassingClass,...,chanceCreationShooting,chanceCreationShootingClass,chanceCreationPositioningClass,defencePressure,defencePressureClass,defenceAggression,defenceAggressionClass,defenceTeamWidth,defenceTeamWidthClass,defenceDefenderLineClass
team_fifa_api_id,,,,,,,,,,,,,,,,,,,,,
240,Atlético Madrid,"[95, 96, 97, 98, 99, 100]",9906,"[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[64, 57, 47, 47, 47, 57]","[Balanced, Balanced, Balanced, Balanced, Balan...","[nan, nan, nan, nan, 52.0, 50.0]","[Little, Little, Little, Little, Normal, Normal]","[30, 54, 51, 51, 51, 50]","[Short, Mixed, Mixed, Mixed, Mixed, Mixed]",...,"[70, 79, 54, 54, 54, 49]","[Lots, Lots, Normal, Normal, Normal, Normal]","[Free Form, Organised, Organised, Organised, O...","[70, 58, 52, 52, 52, 49]","[High, Medium, Medium, Medium, Medium, Medium]","[34, 48, 37, 37, 37, 42]","[Press, Press, Press, Press, Press, Press]","[55, 54, 55, 55, 55, 52]","[Normal, Normal, Normal, Normal, Normal, Normal]","[Offside Trap, Cover, Cover, Cover, Cover, Cover]"
241,FC Barcelona,"[119, 120, 121, 122, 123, 124]",8634,"[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[42, 43, 24, 35, 35, 36]","[Balanced, Balanced, Slow, Balanced, Balanced,...","[nan, nan, nan, nan, 35.0, 35.0]","[Little, Little, Little, Little, Normal, Normal]","[30, 34, 25, 32, 32, 51]","[Short, Mixed, Short, Short, Short, Mixed]",...,"[70, 68, 54, 35, 35, 56]","[Lots, Lots, Normal, Normal, Normal, Normal]","[Free Form, Free Form, Free Form, Free Form, F...","[70, 67, 66, 61, 61, 61]","[High, High, Medium, Medium, Medium, Medium]","[30, 43, 63, 63, 63, 65]","[Contain, Press, Press, Press, Press, Press]","[70, 68, 66, 65, 65, 65]","[Wide, Wide, Normal, Normal, Normal, Normal]","[Offside Trap, Cover, Cover, Cover, Cover, Cover]"
242,RC Deportivo de La Coruña,"[345, 346, 347, 348, 349, 350]",9783,"[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[30, 56, 56, 56, 56, 53]","[Slow, Balanced, Balanced, Balanced, Balanced,...","[nan, nan, nan, nan, 55.0, 55.0]","[Little, Little, Little, Little, Normal, Normal]","[30, 42, 46, 46, 46, 47]","[Short, Mixed, Mixed, Mixed, Mixed, Mixed]",...,"[65, 61, 68, 68, 68, 55]","[Normal, Normal, Lots, Lots, Lots, Normal]","[Organised, Organised, Organised, Organised, O...","[35, 38, 45, 45, 45, 45]","[Medium, Medium, Medium, Medium, Medium, Medium]","[35, 44, 50, 50, 50, 50]","[Press, Press, Press, Press, Press, Press]","[45, 69, 59, 59, 59, 59]","[Normal, Wide, Normal, Normal, Normal, Normal]","[Offside Trap, Cover, Cover, Cover, Cover, Off..."
243,Real Madrid CF,"[1049, 1050, 1051, 1052, 1053, 1054]",8633,"[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[55, 54, 45, 50, 50, 50]","[Balanced, Balanced, Balanced, Balanced, Balan...","[nan, nan, nan, nan, 54.0, 57.0]","[Little, Little, Little, Little, Normal, Normal]","[30, 39, 35, 41, 41, 46]","[Short, Mixed, Mixed, Mixed, Mixed, Mixed]",...,"[70, 67, 73, 72, 69, 63]","[Lots, Lots, Lots, Lots, Lots, Normal]","[Free Form, Free Form, Free Form, Free Form, F...","[65, 68, 49, 39, 39, 52]","[Medium, High, Medium, Medium, Medium, Medium]","[40, 55, 60, 49, 49, 60]","[Press, Press, Press, Press, Press, Press]","[65, 55, 68, 65, 65, 63]","[Normal, Normal, Wide, Normal, Normal, Normal]","[Offside Trap, Cover, Cover, Cover, Cover, Cover]"
244,Real Zaragoza,"[1445, 1446, 1447, 1448, 1449, 1450]",8394,"[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[30, 43, 34, 38, 38, 52]","[Slow, Balanced, Balanced, Balanced, Balanced,...","[nan, nan, nan, nan, 48.0, 52.0]","[Little, Little, Little, Little, Normal, Normal]","[30, 40, 23, 23, 35, 50]","[Short, Mixed, Short, Short, Mixed, Mixed]",...,"[70, 42, 57, 57, 57, 57]","[Lots, Normal, Normal, Normal, Normal, Normal]","[Organised, Organised, Organised, Organised, O...","[40, 38, 51, 51, 51, 48]","[Medium, Medium, Medium, Medium, Medium, Medium]","[30, 40, 46, 46, 46, 43]","[Contain, Press, Press, Press, Press, Press]","[45, 53, 61, 61, 61, 49]","[Normal, Normal, Normal, Normal, Normal, Normal]","[Offside Trap, Cover, Cover, Cover, Cover, Cover]"
260,CD Tenerife,"[1261, 1262, 1263, 1264]",9867,"[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[30, 56, 56, 56]","[Slow, Balanced, Balanced, Balanced]","[nan, nan, 50.0, 50.0]","[Little, Little, Normal, Normal]","[30, 51, 57, 57]","[Short, Mixed, Mixed, Mixed]",...,"[65, 60, 54, 54]","[Normal, Normal, Normal, Normal]","[Organised, Organised, Organised, Organised]","[50, 57, 52, 52]","[Medium, Medium, Medium, Medium]","[30, 50, 50, 50]","[Contain, Press, Press, Press]","[45, 67, 65, 69]","[Normal, Wide, Normal, Wide]","[Cover, Cover, Cover, Cover]"
448,Athletic Club de Bilbao,"[89, 90, 91, 92, 93, 94]",8315,"[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[60, 70, 42, 46, 46, 46]","[Balanced, Fast, Balanced, Balanced, Balanced,...","[nan, nan, nan, nan, 41.0, 46.0]","[Little, Little, Little, Little, Normal, Normal]","[45, 69, 59, 38, 38, 39]","[Mixed, Long, Mixed, Mixed, Mixed, Mixed]",...,"[55, 57, 59, 37, 37, 36]","[Normal, Normal, Normal, Normal, Normal, Normal]","[Organised, Organised, Organised, Free Form, O...","[30, 48, 37, 37, 37, 49]","[Deep, Medium, Medium, Medium, Medium, Medium]","[70, 67, 60, 60, 60, 57]","[Double, Double, Press, Press, Press, Press]","[35, 55, 68, 68, 65, 50]","[Normal, Normal, Wide, Wide, Normal, Normal]","[Cover, Cover, Cover, Cover, Cover, Cover]"
449,Real Betis Balompié,"[1043, 1044, 1045, 1046, 1047, 1048]",8603,"[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[45, 37, 55, 59, 59, 59]","[Balanced, Balanced, Balanced, Balanced, Balan...","[nan, nan, nan, nan, 49.0, 49.0]","[Little, Little, Little, Little, Normal, Normal]","[45, 51, 37, 37, 37, 37]","[Mixed, Mixed, Mixed, Mixed, Mixed, Mixed]",...,"[55, 72, 53, 53, 53, 53]","[Normal, Lots, Normal, Normal, Normal, Normal]","[Free Form, Free Form, Organised, Organised, O...","[50, 42, 58, 58, 58, 58]","[Medium, Medium, Medium, Medium, Medium, Medium]","[45, 40, 49, 49, 49, 49]","[Press, Press, Press, Press, Press, Press]","[55, 53, 58, 58, 58, 58]","[Normal, Normal, Normal, Normal, Normal, Normal]","[Offside Trap, Cover, Cover, Cover, Cover, Cover]"
450,RC Celta de Vigo,"[283, 284, 285, 286, 287, 288]",9910,"[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[35, 43, 53, 53, 53, 55]","[Balanced, Balanced, Balanced, Balanced, Balan...","[nan, nan, nan, nan, 54.0, 59.0]","[Little, Little, Little, Little, Normal, Normal]","[30, 44, 62, 62, 62, 38]","[Short, Mixed, Mixed, Mixed, Mixed, Mixed]",...,"[70, 60, 52, 52, 52, 50]","[Lots, Normal, Normal, Normal, Normal, Normal]","[Organised, Organised, Organised, Free Form, O...","[35, 40, 42, 42, 42, 55]","[Medium, Medium, Medium, Medium, Medium, Medium]","[30, 41, 52, 52, 52, 55]","[Contain, Press, Press, Press, Press, Press]","[50, 47, 68, 68, 65, 59]","[Normal, Normal, Wide, Wide, Normal, Normal]","[Offside Trap, Cover, Cover, Cover, Cover, Cover]"
452,RCD Espanyol,"[395, 396, 397, 398, 399, 400]",8558,"[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[55, 68, 46, 50, 50, 50]","[Balanced, Fast, Balanced, Balanced, Balanced,...","[nan, nan, nan, nan, 52.0, 52.0]","[Little, Little, Little, Little, Normal, Normal]","[40, 55, 44, 44, 44, 44]","[Mixed, Mixed, Mixed, Mixed, Mixed, Mixed]",...,"[70, 54, 40, 40, 40, 40]","[Lots, Normal, Normal, Normal, Normal, Normal]","[Organised, Organised, Organised, Free Form, O...","[70, 51, 37, 37, 37, 37]","[High, Medium, Medium, Medium, Medium, Medium]","[50, 58, 40, 40, 40, 40]","[Press, Press, Press, Press, Press, Press]","[60, 56, 45, 45, 45, 45]","[Normal, Normal, Normal, Normal, Normal, Normal]","[Cover, Cover, Cover, Cover, Cover, Cover]"
453,RCD Mallorca,"[795, 796, 797, 798, 799, 800]",8661,"[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[40, 53, 58, 62, 62, 62]","[Balanced, Balanced, Balanced, Balanced, Balan...","[nan, nan, nan, nan, 53.0, 53.0]","[Little, Little, Little, Little, Normal, Normal]","[40, 52, 57, 57, 57, 57]","[Mixed, Mixed, Mixed, Mixed, Mixed, Mixed]",...,"[50, 53, 53, 53, 53, 53]","[Normal, Normal, Normal, Normal, Normal, Normal]","[Free Form, Free Form, Organised, Organised, O...","[45, 47, 59, 59, 59, 59]","[Medium, Medium, Medium, Medium, Medium, Medium]","[40, 48, 41, 41, 41, 41]","[Press, Press, Press, Press, Press, Press]","[45, 55, 56, 56, 56, 56]","[Normal, Normal, Normal, Normal, Normal, Normal]","[Offside Trap, Cover, Cover, Cover, Cover, Cover]"
456,Racing Santander,"[1020, 1021, 1022, 1023, 1024]",8696,"[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[45, 53, 43, 47, 48]","[Balanced, Balanced, Balanced, Balanced, Balan...","[nan, nan, nan, nan, 52.0]","[Little, Little, Little, Little, Normal]","[55, 56, 44, 44, 47]","[Mixed, Mixed, Mixed, Mixed, Mixed]",...,"[65, 39, 50, 50, 53]","[Normal, Normal, Normal, Normal, Normal]","[Free Form, Organised, Organised, Organised, O...","[45, 47, 50, 50, 51]","[Medium, Medium, Medium, Medium, Medium]","[55, 37, 50, 50, 47]","[Press, Press, Press, Press, Press]","[50, 53, 68, 68, 53]","[Normal, Normal, Wide, Wide, Normal]","[Cover, Cover, Cover, Cover, Cover]"
457,Real Sociedad,"[1055, 1056, 1057, 1058, 1059, 1060]",8560,"[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[40, 54, 24, 28, 35, 60]","[Balanced, Balanced, Slow, Slow, Balanced, Bal...","[nan, nan, nan, nan, 52.0, 52.0]","[Little, Little, Little, Little, Normal, Normal]","[30, 43, 36, 36, 36, 50]","[Short, Mixed, Mixed, Mixed, Mixed, Mixed]",...,"[70, 60, 59, 59, 59, 52]","[Lots, Normal, Normal, Normal, Normal, Normal]","[Organised, Organised, Organised, Organised, O...","[45, 49, 48, 48, 48, 49]","[Medium, Medium, Medium, Medium, Medium, Medium]","[30, 49, 53, 53, 53, 53]","[Contain, Press, Press, Press, Press, Press]","[35, 51, 70, 70, 65, 53]","[Normal, Normal, Wide, Wide, Normal, Normal]","[Offside Trap, Cover, Cover, Cover, Cover, Cover]"
459,Real Sporting de Gijón,"[1199, 1200, 1201, 1202, 1203, 1204]",9869,"[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[70, 68, 51, 55, 55, 55]","[Fast, Fast, Balanced, Balanced, Balanced, Bal...","[nan, nan, nan, nan, 48.0, 48.0]","[Little, Little, Little, Little, Normal, Normal]","[55, 53, 43, 43, 43, 50]","[Mixed, Mixed, Mixed, Mixed, Mixed, Mixed]",...,"[70, 65, 44, 44, 44, 38]","[Lots, Normal, Normal, Normal, Normal, Normal]","[Organised, Organised, Organised, Organised, O...","[70, 58, 36, 36, 36, 45]","[High, Medium, Medium, Medium, Medium, Medium]","[70, 51, 60, 60, 60, 54]","[Double, Press, Press, Press, Press, Press]","[55, 55, 39, 39, 39, 41]","[Normal, Normal, Normal, Normal, Normal, Normal]","[Cover, Cover, Cover, Cover, Cover, Cover]"
461,Valencia CF,"[1308, 1309, 1310, 1311, 1312, 1313]",10267,"[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[30, 41, 20, 20, 30, 35]","[Slow, Balanced, Slow, Slow, Slow, Balanced]","[nan, nan, nan, nan, 45.0, 46.0]","[Little, Little, Little, Little, Normal, Normal]","[30, 40, 35, 35, 35, 35]","[Short, Mixed, Mixed, Mixed, Mixed, Mixed]",...,"[70, 64, 55, 55, 55, 58]","[Lots, Normal, Normal, Normal, Normal, Normal]","[Organised, Free Form, Organised, Organised, O...","[55, 40, 51, 51, 51, 49]","[Medium, Medium, Medium, Medium, Medium, Medium]","[60, 48, 38, 38, 38, 45]","[Press, Press, Press, Press, Press, Press]","[60, 54, 59, 59, 59, 53]","[Normal, Normal, Normal, Normal, Normal, Normal]","[Offside Trap, Cover, Cover, Cover, Cover, Cover]"
462,Real Valladolid,"[1320, 1321, 1322, 1323, 1324, 1325]",10281,"[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[55, 54, 55, 55, 55, 43]","[Balanced, Balanced, Balanced, Balanced, Balan...","[nan, nan, nan, nan, 44.0, 40.0]","[Little, Little, Little, Little, Normal, Normal]","[40, 55, 54, 54, 54, 65]","[Mixed, Mixed, Mixed, Mixed, Mixed, Mixed]",...,"[60, 62, 41, 41, 41, 57]","[Normal, Normal, Normal, Normal, Normal, Normal]","[Organised, Organised, Organised, Organised, O...","[30, 43, 51, 51, 51, 47]","[Deep, Medium, Medium, Medium, Medium, Medium]","[65, 52, 50, 50, 50, 40]","[Press, Press, Press, Press, Press, Press]","[30, 59, 60, 60, 60, 47]","[Narrow, Normal, Normal, Normal, Normal, Normal]","[Cover, Cover, Cover, Cover, Cover, Cover]"
467,SD Eibar,"[366, 367]",8372,"[2014-09-19 00:00:00, 2015-09-10 00:00:00]","[62, 62]","[Balanced, Balanced]","[51.0, 51.0]","[Normal, Normal]","[52, 52]","[Mixed, Mixed]",...,"[64, 52]","[Normal, Normal]","[Organised, Organised]","[37, 37]","[Medium, Medium]","[56, 56]","[Press, Press]","[49, 49]","[Normal, Normal]","[Cover, Cover]"
468,Elche CF,"[378, 379, 380, 381, 382, 383]",10268,"[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[30, 43, 55, 55, 55, 51]","[Slow, Balanced, Balanced, Balanced, Balanced,...","[nan, nan, nan, nan, 47.0, 52.0]","[Little, Little, Little, Little, Normal, Normal]","[30, 39, 73, 73, 69, 48]","[Short, Mixed, Long, Long, Long, Mixed]",...,"[70, 46, 57, 57, 57, 57]","[Lots, Normal, Normal, Normal, Normal, Normal]","[Organised, Organised, Organised, Organised, O...","[50, 40, 49, 49, 49, 49]","[Medium, Medium, Medium, Medium, Medium, Medium]","[45, 39, 51, 51, 51, 51]","[Press, Press, Press, Press, Press, Press]","[45, 51, 58, 58, 58, 58]","[Normal, Normal, Normal, Normal, Normal, Normal]","[Cover, Cover, Cover, Cover, Cover, Cover]"
472,UD Las Palmas,"[666, 667, 668, 669, 670, 671]",8306,"[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[30, 54, 48, 48, 48, 48]","[Slow, Balanced, Balanced, Balanced, Balanced,...","[nan, nan, nan, nan, 55.0, 55.0]","[Little, Little, Little, Little, Normal, Normal]","[30, 56, 44, 44, 44, 44]","[Short, Mixed, Mixed, Mixed, Mixed, Mixed]",...,"[70, 59, 53, 53, 53, 53]","[Lots, Normal, Normal, Normal, Normal, Normal]","[Organised, Organised, Organised, Organised, O...","[35, 48, 53, 53, 53, 53]","[Medium, Medium, Medium, Medium, Medium, Medium]","[45, 56, 39, 39, 39, 39]","[Press, Press, Press, Press, Press, Press]","[45, 67, 57, 57, 57, 57]","[Normal, Wide, Normal, Normal, Normal, Normal]","[Offside Trap, Cover, Cover, Cover, Cover, Cover]"
477,CD Numancia,"[921, 922, 923, 924, 925, 926]",8388,"[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[55, 71, 44, 44, 44, 44]","[Balanced, Fast, Balanced, Balanced, Balanced,...","[nan, nan, nan, nan, 48.0, 48.0]","[Little, Little, Little, Little, Normal, Normal]","[40, 53, 45, 45, 45, 45]","[Mixed, Mixed, Mixed, Mixed, Mixed, Mixed]",...,"[55, 53, 57, 57, 57, 57]","[Normal, Normal, Normal, Normal, Normal, Normal]","[Organised, Organised, Organised, Organised, O...","[30, 40, 50, 50, 50, 50]","[Deep, Medium, Medium, Medium, Medium, Medium]","[55, 49, 46, 46, 46, 46]","[Press, Press, Press, Press, Press, Press]","[55, 55, 62, 62, 62, 62]","[Normal, Normal, Normal, Normal, Normal, Normal]","[Offside Trap, Cover, Cover, Cover, Cover, Cover]"
479,CA Osasuna,"[935, 936, 937, 938, 939, 940]",8371,"[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[35, 55, 34, 38, 38, 38]","[Balanced, Balanced, Balanced, Balanced, Balan...","[nan, nan, nan, nan, 53.0, 53.0]","[Little, Little, Little, Little, Normal, Normal]","[35, 54, 52, 52, 52, 52]","[Mixed, Mixed, Mixed, Mixed, Mixed, Mixed]",...,"[55, 68, 54, 54, 54, 54]","[Normal, Lots, Normal, Normal, Normal, Normal]","[Free Form, Free Form, Organised, Organised, O...","[30, 48, 47, 47, 47, 47]","[Deep, Medium, Medium, Medium, Medium, Medium]","[65, 61, 52, 52, 52, 52]","[Press, Press, Press, Press, Press, Press]","[55, 68, 69, 69, 65, 69]","[Normal, Wide, Wide, Wide, Normal, Wide]","[Cover, Cover, Cover, Cover, Cover, Cover]"
480,Rayo Vallecano,"[1031, 1032, 1033, 1034, 1035, 1036]",8370,"[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[40, 53, 41, 45, 45, 29]","[Balanced, Balanced, Balanced, Balanced, Balan...","[nan, nan, nan, nan, 52.0, 52.0]","[Little, Little, Little, Little, Normal, Normal]","[30, 55, 44, 44, 44, 44]","[Short, Mixed, Mixed, Mixed, Mixed, Mixed]",...,"[70, 61, 47, 47, 47, 47]","[Lots, Normal, Normal, Normal, Normal, Normal]","[Organised, Organised, Organised, Organised, O...","[30, 58, 63, 63, 63, 54]","[Deep, Medium, Medium, Medium, Medium, Medium]","[50, 52, 51, 51, 51, 52]","[Press, Press, Press, Press, Press, Press]","[40, 68, 59, 59, 59, 63]","[Normal, Wide, Normal, Normal, Normal, Normal]","[Offside Trap, Cover, Cover, Cover, Cover, Cover]"
481,Sevilla FC,"[1157, 1158, 1159, 1160, 1161, 1162]",8302,"[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[30, 68, 61, 65, 65, 53]","[Slow, Fast, Balanced, Balanced, Balanced, Bal...","[nan, nan, nan, nan, 53.0, 53.0]","[Little, Little, Little, Little, Normal, Normal]","[30, 58, 65, 65, 65, 53]","[Short, Mixed, Mixed, Mixed, Mixed, Mixed]",...,"[70, 71, 38, 38, 38, 60]","[Lots, Lots, Normal, Normal, Normal, Normal]","[Free Form, Free Form, Organised, Organised, O...","[60, 57, 38, 38, 38, 42]","[Medium, Medium, Medium, Medium, Medium, Medium]","[70, 58, 49, 49, 49, 48]","[Double, Press, Press, Press, Press, Press]","[65, 68, 55, 55, 55, 59]","[Normal, Wide, Normal, Normal, Normal, Normal]","[Offside Trap, Cover, Cover, Cover, Cover, Cover]"
483,Villarreal CF,"[1336, 1337, 1338, 1339, 1340, 1341]",10205,"[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[64, 42, 20, 24, 35, 48]","[Balanced, Balanced, Slow, Slow, Balanced, Bal...","[nan, nan, nan, nan, 42.0, 42.0]","[Little, Little, Little, Little, Normal, Normal]","[30, 41, 26, 26, 35, 36]","[Short, Mixed, Short, Short, Mixed, Mixed]",...,"[70, 70, 58, 58, 58, 55]","[Lots, Lots, Normal, Normal, Normal, Normal]","[Free Form, Free Form, Organised, Organised, O...","[65, 50, 51, 51, 51, 47]","[Medium, Medium, Medium, Medium, Medium, Medium]","[30, 48, 51, 51, 51, 48]","[Contain, Press, Press, Press, Press, Press]","[70, 54, 56, 56, 56, 44]","[Wide, Normal, Normal, Normal, Normal, Normal]","[Offside Trap, Cover, Cover, Cover, Cover, Cover]"
571,RC Recreativo,"[1061, 1062, 1063, 1064, 1065, 1066]",8479,"[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[50, 45, 41, 41, 41, 37]","[Balanced, Balanced, Balanced, Balanced, Balan...","[nan, nan, nan, nan, 53.0, 38.0]","[Little, Little, Little, Little, Normal, Normal]","[40, 58, 54, 54, 54, 43]","[Mixed, Mixed, Mixed, Mixed, Mixed, Mixed]",...,"[50, 52, 23, 23, 35, 37]","[Normal, Normal, Little, Little, Normal, Normal]","[Organised, Organised, Organised, Organised, O...","[35, 39, 40, 40, 40, 40]","[Medium, Medium, Medium, Medium, Medium, Medium]","[55, 39, 49, 49, 49, 49]","[Press, Press, Press, Press, Press, Press]","[40, 66, 62, 62, 62, 54]","[Normal, Normal, Normal, Normal, Normal, Normal]","[Cover, Cover, Cover, Cover, Cover, Cover]"
573,Málaga CF,"[789, 790, 791, 792, 793, 794]",9864,"[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[60, 58, 41, 45, 45, 42]","[Balanced, Balanced, Balanced, Balanced, Balan...","[nan, nan, nan, nan, 42.0, 51.0]","[Little, Little, Little, Little, Normal, Normal]","[55, 54, 36, 36, 36, 36]","[Mixed, Mixed, Mixed, Mixed, Mixed, Mixed]",...,"[70, 61, 50, 50, 50, 50]","[Lots, Normal, Normal, Normal, Normal, Normal]","[Organised, Organised, Organised, Organised, O...","[45, 45, 64, 64, 64, 47]","[Medium, Medium, Medium, Medium, Medium, Medium]","[65, 47, 58, 58, 58, 37]","[Press, Press, Press, Press, Press, Press]","[45, 54, 42, 42, 42, 52]","[Normal, Normal, Normal, Normal, Normal, Normal]","[Cover, Cover, Cover, Cover, Cover, Offside Trap]"
1742,Xerez Club Deportivo,"[1430, 1431, 1432, 1433]",9868,"[2010-02-22 00:00:00, 2011-02-22 00:00:00, 201...","[30, 40, 60, 60]","[Slow, Balanced, Balanced, Balanced]","[nan, nan, nan, nan]","[Little, Little, Little, Little]","[30, 58, 44, 44]","[Short, Mixed, Mixed, Mixed]",...,"[70, 49, 41, 41]","[Lots, Normal, Normal, Normal]","[Organised, Organised, Organised, Organised]","[45, 46, 49, 49]","[Medium, Medium, Medium, Medium]","[50, 52, 54, 54]","[Press, Press, Press, Press]","[45, 67, 50, 50]","[Normal, Wide, Normal, Normal]","[Cover, Cover, Cover, Cover]"